### ISSUE TITLE
Reset RunningInstances to 0

### ISSUE THREAD

**Issue by PandyLegend** [shapecode/cron-bundle#26]
Several times the RunningInstances value is not being reset upon completion of a command, even though the command has completed. This means the command will never run again unless I manually reset the value.
Is it possible to have some mechanism to either check if a command is really running or not and set the value back to 0 if not, or set a timeout period where it will set back to zero if stuck on 1 for x minutes?

**Comment by PandyLegend** [comment]
Further observation.
I have 5 commands all set to run every minute. The first one runs fine and the RunningInstances is reset after completion, however the subsequent 4 do not get reset. All commands are basically the same and if I change the order they get executed, it is always the first one that resets the RunningInstances value and subsequent ones do not.

Looking into the code, it appears as though it is checking for when the process is no longer running in the system and that is when it resets the value. My suspicion is that when running simultaneous commands, it is using a single process and so the end of that process is only picked up by the first instance, leaving the subsequent ones stuck.

@nicklog  What do you think?

**Comment by nicklog** [comment]
I have to see your crons and configurations. So its a little bit hard to find the bug.
Could you provide some data?

**Comment by frostieDE** [comment]
@nicklog Can you provide some information about how to investigate into the crons? I am facing the same problem.

**Comment by nicklog** [comment]
@frostieDE Hey, sorry for my late anwser. For the moment i can not find out the issue :-/

**Comment by frostieDE** [comment]
I suppose it may have something to do with timeouts. My scenario is as follows:

An HTTP request is done and the corresponding controller starts the `shapecode:cron:run` command like this:

```php
    /**
     * @Route("/cron", methods={"GET"})
     */
    public function run(KernelInterface $kernel) {
        $application = new Application($kernel);
        $application->setAutoExit(false);

        $input = new StringInput('shapecode:cron:run');

        $output = new BufferedOutput(
            OutputInterface::VERBOSITY_NORMAL,
            true
        );
        $application->run($input, $output);

        $content = $output->fetch();
        $converter = new AnsiToHtmlConverter();

        return $this->render('@Common/cron/output.html.twig', [
            'output' => $converter->convert($content)
        ]);
    }
```
All cronjobs are started correctly, but here is the catch: my HTTP request has an 30s execution limit. So the request is killed by the underlying cronjob processes are not done yet (whyever?!). I am not sure whether they are killed as well or still run until they are finished. But the thing is: the number of running instances is not decreased, because of the 30s execution limit.

I suggest adding a configuration parameter so we can utilize the [timeout functionality of the Process component](https://symfony.com/doc/current/components/process.html#process-timeout).

WDYT?

**Comment by frostieDE** [comment]
@nicklog Is there an ETA on when this feature is released? :-)

**Comment by nicklog** [comment]
@frostieDE Hey, you should already be able to use v5.0@dev version.
Perhaps you could then tell me if everything is going to your satisfaction

**Comment by frostieDE** [comment]
Thanks for the clarification! I will test the dev branch and give feedback :-)
